from __future__ import annotations

from pathlib import Path
from typing import Any


DEFAULT_MAP_COLOR = "#2E2E2E"
DEFAULT_BACKGROUND_COLOR = "#1F1F1F"
DEFAULT_GRID_CELL_SIZE_FT = 8.0
DEFAULT_GRID_LINE_THICKNESS_PX = 1.0
DEFAULT_GRID_OPACITY = 0.45
DEFAULT_GRID_COLOR = "#000000"


def build_default_settings(project_root: Path) -> dict[str, Any]:
    adventures_root = project_root / "adventures"
    return {
        "adventures_root": str(adventures_root),
        "default_scene": {
            "map": {
                "enabled": True,
                "type": "color",
                "value": DEFAULT_MAP_COLOR,
                "autoplay": True,
                "loop": True,
                "mute": True,
            },
            "background": {
                "enabled": True,
                "type": "color",
                "value": DEFAULT_BACKGROUND_COLOR,
                "autoplay": True,
                "loop": True,
                "mute": True,
            },
            "grid": {
                "enabled": True,
                "cell_size_ft": DEFAULT_GRID_CELL_SIZE_FT,
                "line_thickness_px": DEFAULT_GRID_LINE_THICKNESS_PX,
                "opacity": DEFAULT_GRID_OPACITY,
                "color": DEFAULT_GRID_COLOR,
            },
        },
        "ui": {
            "left_panel_width": 260,
            "left_reveal_zone": 300,
        },
        "tools": {
            "brush_size_ft_min": 1.0 / 6.0,
            "brush_size_ft_max": 25.0,
        },
        "undo": {
            "max_steps": 50,
        },
        "hotkeys": {
            "pen": "P",
            "eraser": "E",
            "fill": "F",
            "hex_select": "H",
            "measure": "M",
            "undo": "Ctrl+Z",
            "fullscreen": "F11",
            "next_scene": "PageDown",
            "previous_scene": "PageUp",
            "save_scene": "Ctrl+S",
        },
        "dice_styles": {},
        "dice_style_templates": {
            "user": [None] * 10,
            "damage": [
                {
                    "scalePercent": 100,
                    "color": "#C8C8C8",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#F3F3F3",
                    "gradientSharpness": 58,
                    "gradientOffset": 50,
                    "fontColor": "#1F2228",
                    "textStrokeColor": "#F0F3FA",
                    "textGlowRadius": 90,
                    "textGlowOpacity": 85,
                    "edgeColor": "#7A7E86",
                    "edgeWidth": 1.2,
                },
                {
                    "scalePercent": 100,
                    "color": "#D35A28",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#FFD08C",
                    "gradientSharpness": 64,
                    "gradientOffset": 52,
                    "fontColor": "#2A140C",
                    "textStrokeColor": "#FFE3A8",
                    "textGlowRadius": 110,
                    "textGlowOpacity": 105,
                    "edgeColor": "#7A2315",
                    "edgeWidth": 1.4,
                },
                {
                    "scalePercent": 100,
                    "color": "#5F6CE0",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#C7D0FF",
                    "gradientSharpness": 56,
                    "gradientOffset": 50,
                    "fontColor": "#151933",
                    "textStrokeColor": "#D9E2FF",
                    "textGlowRadius": 108,
                    "textGlowOpacity": 96,
                    "edgeColor": "#2E356E",
                    "edgeWidth": 1.2,
                },
                {
                    "scalePercent": 100,
                    "color": "#E4CE63",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#FFF7BE",
                    "gradientSharpness": 62,
                    "gradientOffset": 48,
                    "fontColor": "#2A240F",
                    "textStrokeColor": "#FFF4B0",
                    "textGlowRadius": 116,
                    "textGlowOpacity": 108,
                    "edgeColor": "#8B7422",
                    "edgeWidth": 1.3,
                },
                {
                    "scalePercent": 100,
                    "color": "#5C4A6A",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#A296B8",
                    "gradientSharpness": 60,
                    "gradientOffset": 53,
                    "fontColor": "#F0EAF8",
                    "textStrokeColor": "#2B1F36",
                    "textGlowRadius": 92,
                    "textGlowOpacity": 78,
                    "edgeColor": "#2D2236",
                    "edgeWidth": 1.3,
                },
                {
                    "scalePercent": 100,
                    "color": "#8A5FD6",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#E1CCFF",
                    "gradientSharpness": 57,
                    "gradientOffset": 50,
                    "fontColor": "#26173A",
                    "textStrokeColor": "#F0E3FF",
                    "textGlowRadius": 122,
                    "textGlowOpacity": 110,
                    "edgeColor": "#4B2F7B",
                    "edgeWidth": 1.2,
                },
                {
                    "scalePercent": 100,
                    "color": "#4D8DF0",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#D8EBFF",
                    "gradientSharpness": 58,
                    "gradientOffset": 50,
                    "fontColor": "#12243D",
                    "textStrokeColor": "#E4F1FF",
                    "textGlowRadius": 114,
                    "textGlowOpacity": 102,
                    "edgeColor": "#224D83",
                    "edgeWidth": 1.3,
                },
                {
                    "scalePercent": 100,
                    "color": "#8CCEF1",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#E8F9FF",
                    "gradientSharpness": 54,
                    "gradientOffset": 48,
                    "fontColor": "#163147",
                    "textStrokeColor": "#F6FDFF",
                    "textGlowRadius": 126,
                    "textGlowOpacity": 116,
                    "edgeColor": "#FFFFFF",
                    "edgeWidth": 1.6,
                },
                {
                    "scalePercent": 100,
                    "color": "#6FAF2C",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#D8FF8A",
                    "gradientSharpness": 63,
                    "gradientOffset": 53,
                    "fontColor": "#1A2D0D",
                    "textStrokeColor": "#EDFFC8",
                    "textGlowRadius": 118,
                    "textGlowOpacity": 104,
                    "edgeColor": "#2D5F15",
                    "edgeWidth": 1.3,
                },
                {
                    "scalePercent": 100,
                    "color": "#4A7A44",
                    "gradientEnabled": True,
                    "gradientCenterColor": "#98D08E",
                    "gradientSharpness": 58,
                    "gradientOffset": 52,
                    "fontColor": "#102012",
                    "textStrokeColor": "#D0F0C8",
                    "textGlowRadius": 104,
                    "textGlowOpacity": 94,
                    "edgeColor": "#20391F",
                    "edgeWidth": 1.2,
                },
            ],
        },
    }
